### ISSUE TITLE
Maybe translate to English

### ISSUE THREAD

**Issue by tianlu1677** [renny-ren/ai-chat#15]
Hi, I don't know why you opened the resource. If you just want more people to use it, maybe translate it into English so that more people can understand.

**Comment by renny-ren** [comment]
Thanks for your suggestion!
This is a project I built last year as a hobby, and I have no time working on this at the moment.
Yes I agree with you that translating to English is a good way to promote it.

**Comment by tianlu1677** [comment]
Do you have any plans to upgrade this project in the coming months?

In China, there isn't a specific market for AI web chat windows because many big companies are focusing on personalized approaches. 

Maybe target businesses could be a better choice.

**Comment by renny-ren** [comment]
I have no plan to upgrade this project for the time being, there're too many homogenous products there.

Feel free to do it if you're interested.
